using Usagi.ToolCore.Audio;
using Xunit;

namespace Usagi.ToolCore.Tests.Audio;

public sealed partial class FsidBuilderTests
{
    [Fact]
    public void ParseLegacyYaml_ReadsSoundFilesAndDefaults()
    {
        var bank = AudioBankYamlParser.ParseFile(FixturePath("minimal-legacy.yml"));

        Assert.Single(bank.SoundFiles);
        var sound = bank.SoundFiles[0];
        Assert.Equal("LASER_SHOT", sound.EnumName);
        Assert.Equal("laser_shot", sound.Filename);
        Assert.Equal(1.0f, sound.Volume);
        Assert.Equal(1000.0f, sound.MaxDistance);
        Assert.Equal(1, sound.AudioType);
        Assert.Equal(128, sound.Priority);
    }

    [Theory]
    [InlineData("LASER_SHOT", "LASER_SHOT", 615283986u)]
    [InlineData("Z_LAST", "Z_LAST", 4221454624u)]
    [InlineData(" spaced name ", "spaced_name", 1623057719u)]
    [InlineData("lowercase", "lowercase", 4265431538u)]
    public void ComputeSoundCrc_MatchesLegacyBuilder(string enumName, string normalizedName, uint expectedCrc)
    {
        Assert.Equal(normalizedName, FsidBuilder.NormalizeSoundName(enumName));
        Assert.Equal(expectedCrc, FsidBuilder.ComputeSoundCrc(enumName));
    }

    [Fact]
    public void WriteHeader_MatchesLegacyGoldenOutput()
    {
        var bank = AudioBankYamlParser.ParseFile(FixturePath("minimal-legacy.yml"));

        var header = FsidBuilder.WriteHeader(bank, "_CLR_TEST_AUDIO_FSID_", "TestAudio");

        Assert.Equal(Normalize(File.ReadAllText(FixturePath("expected.h"))), Normalize(header));
    }

    [Fact]
    public void WriteProto_MatchesLegacyGoldenOutput()
    {
        var bank = AudioBankYamlParser.ParseFile(FixturePath("minimal-legacy.yml"));

        var proto = FsidBuilder.WriteProto(bank, "TestAudio", new DateTimeOffset(2026, 5, 13, 20, 0, 0, TimeSpan.Zero));

        Assert.Equal(Normalize(File.ReadAllText(FixturePath("expected.proto"))), NormalizeProto(proto));
    }

    [Fact]
    public void WriteProto_PreservesOrderAndSignedCrcValues()
    {
        var bank = AudioBankYamlParser.ParseFile(FixturePath("edge-legacy.yml"));

        var proto = FsidBuilder.WriteProto(bank, "EdgeAudio", new DateTimeOffset(2026, 5, 13, 20, 0, 0, TimeSpan.Zero));

        Assert.Equal(Normalize(File.ReadAllText(FixturePath("expected-edge.proto"))), NormalizeProto(proto));
    }

    [Fact]
    public void WriteHeader_PreservesOrderAndUnsignedCrcValues()
    {
        var bank = AudioBankYamlParser.ParseFile(FixturePath("edge-legacy.yml"));

        var header = FsidBuilder.WriteHeader(bank, "_CLR_EDGE_AUDIO_FSID_", "EdgeAudio");

        Assert.Equal(Normalize(File.ReadAllText(FixturePath("expected-edge.h"))), Normalize(header));
    }

    [Fact]
    public void WriteHeader_RejectsDuplicateNormalizedNames()
    {
        var bank = AudioBankYamlParser.Parse("""
            AudioBank:
              soundFiles:
                - enumName: one sound
                  filename: one
                - enumName: one_sound
                  filename: two
            """);

        var error = Assert.Throws<InvalidOperationException>(() =>
            FsidBuilder.WriteHeader(bank, "_TEST_", "TestAudio"));
        Assert.Contains("Duplicate audio enum name", error.Message, StringComparison.Ordinal);
    }

    private static string FixturePath(string fileName)
    {
        var root = FindRepoRoot();
        return Path.Combine(root, "Tools", "Tests", "AudioToolReverseEngineering", "FSIDBuilderSmoke", fileName);
    }

    private static string FindRepoRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (Directory.Exists(Path.Combine(directory.FullName, "Tools", "Tests", "AudioToolReverseEngineering")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("Could not locate Usagi repository root.");
    }

    private static string NormalizeProto(string value)
    {
        value = value.Replace("\r\n", "\n", StringComparison.Ordinal);
        value = value.Replace("Copyright © Vitei", "Copyright (c) Vitei", StringComparison.Ordinal);
        return TimestampLineRegex().Replace(value, "//  Auto-generated by Usagi Audio Tool at <timestamp>");
    }

    private static string Normalize(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal);

    [System.Text.RegularExpressions.GeneratedRegex("//  Auto-generated by Usagi Audio Tool at .+")]
    private static partial System.Text.RegularExpressions.Regex TimestampLineRegex();
}
