param(
    [string]$RepoRoot = (Resolve-Path "$PSScriptRoot\..\..\..\..").Path
)

$ErrorActionPreference = 'Stop'

$tool = Join-Path $RepoRoot 'Tools\AudioTool\FSIDBuilder.exe'
$inputFile = Join-Path $PSScriptRoot 'minimal-legacy.yml'
$outDir = Join-Path $PSScriptRoot 'out'
$protoOut = Join-Path $outDir 'minimal.proto'
$headerOut = Join-Path $outDir 'minimal.h'

New-Item -ItemType Directory -Force -Path $outDir | Out-Null
Remove-Item -LiteralPath $protoOut, $headerOut -Force -ErrorAction SilentlyContinue

& $tool -i $inputFile -o $protoOut -e TestAudio -g _CLR_TEST_AUDIO_FSID_ -p
if ($LASTEXITCODE -ne 0) {
    throw "FSIDBuilder proto generation failed with exit code $LASTEXITCODE"
}

& $tool -i $inputFile -o $headerOut -e TestAudio -g _CLR_TEST_AUDIO_FSID_
if ($LASTEXITCODE -ne 0) {
    throw "FSIDBuilder header generation failed with exit code $LASTEXITCODE"
}

$proto = Get-Content -Raw -LiteralPath $protoOut
$proto = $proto -replace '//  Auto-generated by Usagi Audio Tool at .+', '//  Auto-generated by Usagi Audio Tool at <timestamp>'
$proto = $proto -replace 'Copyright . Vitei', 'Copyright (c) Vitei'
$proto = $proto -replace "`r`n", "`n"
$expectedProto = Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'expected.proto')
$expectedProto = $expectedProto -replace "`r`n", "`n"
if ($proto -ne $expectedProto) {
    throw "Generated proto did not match expected.proto"
}

$header = Get-Content -Raw -LiteralPath $headerOut
$header = $header -replace "`r`n", "`n"
$expectedHeader = Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'expected.h')
$expectedHeader = $expectedHeader -replace "`r`n", "`n"
if ($header -ne $expectedHeader) {
    throw "Generated header did not match expected.h"
}

Write-Host 'FSIDBuilder smoke fixture matched expected output.'
